create table if not exists user_account (
    id bigint generated by default as identity primary key,
    user_name varchar(100) not null,
    password_hash varchar(255) not null,
    user_role varchar(30) not null,
    enabled boolean not null,
    locked boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create unique index if not exists uk_user_account_user_name
    on user_account (user_name);
